Getlog
EVerest/libocpp pull request #111
Opened 2023-07-04 14:43 UTC by maaikez

Implementation of GetLog, based on 1.6 implementation.

2023-07-05 20:57 UTC, Pietfried requested changes
Looks pretty good, only some minor changes requested.

2023-07-05 20:57 UTC, Pietfried commented on lib/ocpp/v201/charge_point.cpp
> +#include "ocpp/v201/messages/LogStatusNotification.hpp"
we can include with <>

2023-07-05 20:57 UTC, Pietfried commented on lib/ocpp/v201/charge_point.cpp
> +    this->send_async<LogStatusNotificationRequest>(call);
this can and should be
 `this->send<LogStatusNotificationRequest>(call);`

2023-07-06 09:58 UTC, maaikez commented
> Looks pretty good, only some minor changes requested.

Done!

2023-07-06 12:54 UTC, Pietfried approved these changes

2023-07-10 12:47 UTC, merged