Feature/n09 n10
EVerest/libocpp pull request #248
Opened 2023-11-07 09:41 UTC by Pietfried

2023-11-07 10:05 UTC, marcemmers requested changes

2023-11-07 10:05 UTC, marcemmers commented on lib/ocpp/v201/charge_point.cpp
> +    if (!msg.customerCertificate.has_value() and !msg.idToken.has_value() and !msg.customerIdentifier.has_value()) {
else if instead? Or is the second if higher priority than the first one?

2023-11-07 10:05 UTC, marcemmers commented on lib/ocpp/v201/charge_point.cpp
> +            data = data.substr(0, max_customer_information_data_length);
This is a bit of a nitpick but doing an erase would be more efficient here. You are now first creating a copy and then removing the original string.

```suggestion
            data.erase(max_customer_information_data_length);
```

2023-11-07 11:50 UTC, Pietfried commented on lib/ocpp/v201/charge_point.cpp
> +const auto DEFAULT_MAX_CUSTOMER_INFORMATION_DATA_LENGTH = 51200;
Its an optional variable in the device model in the InternalCtrlr, so if its not present we need a default. Not sure if we want to define this as required

2023-11-07 15:59 UTC, Pietfried commented on lib/ocpp/v201/charge_point.cpp
> +        // Recursively send next sequence
done

2023-11-08 10:05 UTC, marcemmers approved these changes

2023-11-08 10:48 UTC, merged