EV 355: part II: update schemas and enforce required property
EVerest/libocpp pull request #272
Opened 2023-11-17 13:54 UTC by klemmpnx

This PR:
- update OCPP 201 standardized schema via script:
- add variable WebsocketPongTimeout in schema (already used in ChargePoint / manually added to 
- corrects usage of required "SecurityCtrlrIdentity" in "SecurityCtrlr" (key must be property key not variable name)
- add new struct RequiredComponentVariable as subclass of ComponentVariable for required variables (via script)
- adjust usages in ChargePoint:
   -  get_latest_meter_value_filtered requires "RequiredComponentVariable" (no further adaptions required)
   -  `authorize_req` does not set cacheExpiryDateTime if AuthCacheLifeTime not set (in accordance with spec; this would have failed before if this non-required variable had not been given)

2023-11-22 15:12 UTC, Pietfried requested changes

2023-11-22 15:12 UTC, Pietfried commented on lib/ocpp/v201/charge_point.cpp
> +    }
```suggestion
```

This should be fixed with: https://github.com/EVerest/libocpp/commit/463975f05a91af41e4b09934bda85f6507db368b

2023-11-23 14:13 UTC, klemmpnx commented
@Pietfried : applied your changes, rebased and tested again

2023-11-23 19:53 UTC, Pietfried approved these changes

2023-11-23 19:57 UTC, Pietfried requested changes
default ciphersuites have been changed in the meantime:
https://github.com/EVerest/libocpp/pull/274

2023-11-23 19:57 UTC, Pietfried commented on config/v201/component_schemas/standardized/InternalCtrlr.json
> +        "valuesList": "ECDHE-ECDSA-AES128-GCM-SHA256,ECDHE-ECDSA-AES256,GCM-SHA384,AES128-GCM-SHA256,AES256-GCM-SHA384,TLS_AES_256_GCM_SHA384,TLS_AES_128_GCM_SHA256",
```suggestion
        "valuesList": "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-GCM-SHA384",
```

2023-11-23 19:57 UTC, Pietfried commented on config/v201/component_schemas/standardized/InternalCtrlr.json
> +        "valuesList": "TLS_AES_256_GCM_SHA384,TLS_AES_128_GCM_SHA256",
```suggestion
        "valuesList": "TLS_AES_256_GCM_SHA384:TLS_AES_128_GCM_SHA256",
```

2023-11-27 13:51 UTC, Pietfried approved these changes

2023-11-27 14:02 UTC, merged