Refactoring of Authorization Process and Event Handling
EVerest/libocpp pull request #41
Opened 2022-09-20 19:05 UTC by Pietfried

refactored libocpp
- removed ChargingSessionHandler and ChargingSession class
- TransactionHandler replaces ChargingSessionHandler - there is no need in ocpp to keep track of a session in detail
- libocpp now initiates less operations, state changes, transactions itself but is therefore more event driven by the registered callbacks
- reservation handling has almost been completely removed
- Simplified authorization process and removed relation between authorization and transaction
- changed firmware and log upload handling to handling with new system and ocpp module

Signed-off-by: pietfried <piet.goempel@pionix.de>

- cleaned up cmake files
- added cmake config style support for install target
- EDM compatibility

Signed-off-by: aw <aw@pionix.de>
Signed-off-by: Kai-Uwe Hermann <kai-uwe.hermann@pionix.de>
Co-authored-by: Kai-Uwe Hermann <kai-uwe.hermann@pionix.de>

2022-09-20 19:05 UTC, Pietfried commented
Should be merged with https://github.com/EVerest/everest-core/pull/105

2022-09-21 07:24 UTC, hikinggrass requested changes

2022-09-21 07:24 UTC, hikinggrass commented on lib/ocpp1_6/charge_point.cpp
> +    auto auth_status = AuthorizationStatus::Invalid;
This variable is set to Invalid here and never updated

2022-09-21 07:24 UTC, hikinggrass commented on lib/ocpp1_6/charge_point.cpp
>          if (auth_status == AuthorizationStatus::Accepted) {
since auth_status is never updated this check will always fail

2022-09-21 14:22 UTC, hikinggrass approved these changes

2022-09-22 07:29 UTC, merged