Feature/variable monitoring messages
EVerest/libocpp pull request #665
Opened 2024-06-10 10:48 UTC by AssemblyJohn

## Describe your changes

Handling of monitoring messages with dispatch to the device model.

## Issue ticket number and link

Depends on: https://github.com/EVerest/libocpp/pull/653
Issue: https://github.com/EVerest/libocpp/issues/640

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have made corresponding changes to the documentation
- [ ] If OCPP 2.0.1: I have updated the [OCPP 2.0.1 status document](https://github.com/EVerest/libocpp/tree/main/doc/ocpp_201_status.md)
- [ ] I read the [contribution documentation](https://github.com/EVerest/EVerest/blob/main/CONTRIBUTING.md) and made sure that my changes meet its requirements

2024-06-19 06:54 UTC, Pietfried requested changes

2024-06-19 06:54 UTC, Pietfried commented on lib/ocpp/v201/charge_point.cpp
> +                }
The device model storage implementation currently doesn't throw `QueryExecutionException`, this is to be added in a subsequent PR 

We have an abstraction layer for the DeviceModelStorage, so we probably do not want to define Device Model specific exceptions for these cases

2024-06-19 06:54 UTC, Pietfried commented on lib/ocpp/v201/charge_point.cpp
> +    }
Same here

2024-06-19 06:54 UTC, Pietfried commented on lib/ocpp/v201/charge_point.cpp
> +    }
Same here

2024-06-19 06:54 UTC, Pietfried commented on lib/ocpp/v201/charge_point.cpp
> +    }
Same here

2024-06-19 06:54 UTC, Pietfried commented on lib/ocpp/v201/device_model_storage_sqlite.cpp
> +int32_t DeviceModelStorageSqlite::clear_custom_variable_monitors() {
Please add a test for `clear_custom_variable_monitors`

2024-06-19 06:54 UTC, Pietfried commented on lib/ocpp/v201/charge_point.cpp
> +    }
Is the `msg.monitoringBase` ever not valid?

2024-06-19 06:54 UTC, Pietfried commented on lib/ocpp/v201/charge_point.cpp
> +            // set by the CSMS) on 'FactoryDefault' too
Yes we should, see N03.FR.04 . This was also clarified with OCA

2024-06-19 06:54 UTC, Pietfried commented on lib/ocpp/v201/charge_point.cpp
> +void ChargePoint::handle_get_variable_monitoring_req(Call<GetMonitoringReportRequest> call) {
function name should be `handle_get_monitoring_report_req`

2024-06-19 06:54 UTC, Pietfried commented on lib/ocpp/v201/charge_point.cpp
> +
You can implement `N02.FR.07` similar to https://github.com/EVerest/libocpp/blob/main/lib/ocpp/v201/charge_point.cpp#L2295

2024-06-19 06:54 UTC, Pietfried commented on lib/ocpp/v201/charge_point.cpp
> +
You can implement N04.FR.09 similar to https://github.com/EVerest/libocpp/blob/main/lib/ocpp/v201/charge_point.cpp#L2295

2024-06-19 10:06 UTC, AssemblyJohn commented
All comments have been implemented.

As a note, due to heavy modifications, almost all the modifications in the production-preparation branch probably have to be re-done (a rebase would be too difficult with so many divergent implementation parts): https://github.com/EVerest/libocpp/tree/feature/variable-monitoring-messages-notifications

My suggestion would be to freeze other spec-based fixes, and move them to the final production branch.

2024-06-20 18:17 UTC, Pietfried requested changes
Just a couple of minor things

2024-06-21 05:39 UTC, AssemblyJohn commented on lib/ocpp/v201/charge_point.cpp
> +    } catch (const DeviceModelStorageError& e) {
I don't understand the request, we're catching a DatabaseException there: https://github.com/EVerest/libocpp/blob/7d456bfec6105eb3dbb7edba3dafae22bf0d2ef1/lib/ocpp/v201/charge_point.cpp#L412

2024-06-21 05:44 UTC, AssemblyJohn commented on lib/ocpp/v201/charge_point.cpp
> +                } catch (const DeviceModelStorageError& e) {
It seems that in the main there has been added a transaction that can throw a 'DeviceModelStorageError': https://github.com/EVerest/libocpp/blob/9d605a925e494e8e8893559e4fe3ef182a9705ef/lib/ocpp/v201/device_model_storage_sqlite.cpp#L209

2024-06-21 05:46 UTC, AssemblyJohn commented on lib/ocpp/v201/charge_point.cpp
> +using DatabaseException = ocpp::common::DatabaseException;
There seem to be more places where this is used, like the `message_queue.hpp`. In principle still using the `QueryExecException` should not change any of the current functionality.

2024-06-21 08:52 UTC, merged