fix error and update example
EVerest/libocpp pull request #74
Opened 2023-02-25 04:42 UTC by Afronut

- in database_handler.cpp the boost optional value expiryDate will not be initialized on idTag if experyDate is not provided or tag  does not have such a date. However, in the chargepoint->validate_against_cache_entries, value() is called on the returned idtag (a boost optional ) from  get_authorization_cache_entry. This will always throw.
- Update the chargepoint example because parameters of he function on_session_started and on_session_stopped has changed

2023-02-25 04:49 UTC, Afronut commented
[boost reference](https://www.boost.org/doc/libs/1_34_0/libs/optional/doc/optional.html)

2023-02-27 10:34 UTC, Pietfried requested changes
Thanks for the fixes to the build examples.

Please remove the changes to the database_handler.cpp and then we can merge.

2023-02-27 10:34 UTC, Pietfried commented on lib/ocpp/common/database_handler.cpp
> +    // if expiry date is not set, calling has_value() on the returned optional will return true, but calling value()
Calling has_value() on an boost:optional will return false if the value of the optional is not set, so setting id_tag_info.expiryDate = boost::none is not necessary

2023-02-27 11:44 UTC, Afronut commented
I will remove it however the client crash when local whitelist is enabled and the server send tags with no expiration so store locally. I have tried with Steve server
I can create a issue.

2023-02-27 12:25 UTC, Pietfried commented
> I will remove it however the client crash when local whitelist is enabled and the server send tags with no expiration so store locally. I have tried with Steve server I can create a issue.

Ok, I tried to reproduce it but could not get the same result. Please create a ticket with further information of your general setup / config file etc. so that we can try to reproduce the error.

2023-03-01 11:27 UTC, Afronut commented
I have removed the update to database handler

2023-03-01 12:19 UTC, Pietfried approved these changes

2023-03-01 12:20 UTC, merged