Folkengine/k08 octt test failure
EVerest/libocpp pull request #803
Opened 2024-09-25 16:11 UTC by folkengine

## Describe your changes

Unit test duplicating the OCTT integration test suite TC_K_41_CS test. 

The `CompositeSchedule` test scenario is compromised of three zero stack level Profiles:

- Absolute ChargingStationMaxProfile with a duration of 86404 and one
chargingSchedulePeriod.
- Absolute TxDefaultProfile with a duration of 304 and 5 periods.
- Absolute TxProfile with a duration of 264 and 5 periods.
It also includes the original log for the test.

While this test failed on its original run, it is passing against the current main branch. This could be because of several reasons:

1. The run was against an earlier version of the code and the issue was fixed through our updates.
2. The parameters passed in for the test are off so that it's a false positive.

## Issue ticket number and link

[issues/188](https://github.com/US-JOET/base-camp/issues/188)

## Checklist before requesting a review
- [X] I have performed a self-review of my code
- [ ] I have made corresponding changes to the documentation
- [ ] If OCPP 2.0.1: I have updated the [OCPP 2.0.1 status document](https://github.com/EVerest/libocpp/tree/main/doc/ocpp_201_status.md)
- [X] I read the [contribution documentation](https://github.com/EVerest/EVerest/blob/main/CONTRIBUTING.md) and made sure that my changes meet its requirements

2024-09-30 05:37 UTC, shankari approved these changes
LGTM! I assume @Pietfried will run this against OCTT again once this is merged.

2024-10-05 18:13 UTC, Pietfried commented
> LGTM! I assume @Pietfried will run this against OCTT again once this is merged.

`TC_K_41_CS` still fails but the reason for this is not composite schedule calculation. The issue is described here: https://github.com/EVerest/libocpp/issues/819 . With the suggested change described within the `Anything Else?` section of that issue, the test case passed.

2024-10-05 18:15 UTC, Pietfried approved these changes

2024-10-05 18:19 UTC, Pietfried requested changes
Thanks for adding this as a unit test!

lgtm except for the octt log which I would not check in.

2024-10-05 18:19 UTC, Pietfried commented on tests/lib/ocpp/v201/json/OCCT_TC_K_41_CS/everest-sil_TC_K_41_CS2024-08-21T12_24_30.733616.log.txt
> +Test Case Name : TC_K_41_CS
I suggest to remove this octt log since I dont see that it provides any value.

2024-10-05 18:19 UTC, Pietfried commented on tests/lib/ocpp/v201/json/OCCT_TC_K_41_CS/README.md
> +This folder also contains the OCCT log file of the original failing test run.
And remove this line once the log file has been removed.

2024-10-07 13:02 UTC, folkengine commented
> Thanks for adding this as a unit test!
> 
> lgtm except for the octt log which I would not check in.

@Pietfried my pleasure. Changes made.

2024-10-07 15:51 UTC, Pietfried approved these changes

2024-10-07 15:52 UTC, merged