Add coverage and use reuable workflow from everest-ci
EVerest/libocpp pull request #858
Opened 2024-11-04 21:05 UTC by hikinggrass

## Describe your changes

## Issue ticket number and link

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] I have made corresponding changes to the documentation
- [ ] If OCPP 2.0.1: I have updated the [OCPP 2.0.1 status document](https://github.com/EVerest/libocpp/tree/main/doc/ocpp_201_status.md)
- [x] I read the [contribution documentation](https://github.com/EVerest/EVerest/blob/main/CONTRIBUTING.md) and made sure that my changes meet its requirements

2024-11-05 07:40 UTC, andistorm requested changes

2024-11-05 07:40 UTC, andistorm commented on .ci/build-kit/scripts/compile.sh
Could you add a check for the return values, please? Especially in the case of cmake is failing the script would continue since there is no `set -e`

2024-11-05 07:40 UTC, andistorm commented on .ci/build-kit/scripts/compile.sh
> +ninja -j$(nproc) -C build
```suggestion
ninja -C build
```

`-j$(nproc)` can be omitted, because ninja uses this as default anyway

2024-11-05 07:40 UTC, andistorm commented on .ci/build-kit/scripts/run_unit_tests.sh
> +set -e
```suggestion
```
Is there a reason for this line?

2024-11-05 08:03 UTC, hikinggrass commented on .ci/build-kit/scripts/compile.sh
done

2024-11-05 08:27 UTC, andistorm requested changes

2024-11-05 08:27 UTC, andistorm commented on .github/workflows/build_and_test.yaml
> +      run_integration_tests: false
```suggestion
      runner: ${{ inputs.runner || 'ubuntu-22.04' }}
      artifact_deploy_target_repo: EVerest/everest.github.io
      run_coverage: true
      do_not_run_coverage_badge_creation: false
      run_install_wheels: false
      run_integration_tests: false
      ctest_report_path: ctest-report
      coverage_report_path: gcovr-coverage
      coverage_xml_path: gcovr-coverage-xml.xml
```

2024-11-06 11:09 UTC, maaikez commented
Where can we see the coverage on github and how can we run the coverage tool offline, and where is it stored locally then? Maybe add some documentation for this?

2024-11-07 09:24 UTC, maaikez approved these changes
It is very nice and works well.

One minor detail:
After coverage is generated, I see this message:
Open ./ocpp_gcovr_coverage/index.html in your browser to view the coverage report.

But it is actually in ./_deps/libocpp-build/ocpp_gcovr_coverage/index.html

Would it be possible to print the whole path there? Then it is easy to copy paste and directly put it in the browser. I could not find this line in the pull request? 

But that's minor, would be nice if it's easy, otherwise it's ok like this.

2024-11-11 11:24 UTC, hikinggrass commented
> It is very nice and works well.
> 
> One minor detail: After coverage is generated, I see this message: Open ./ocpp_gcovr_coverage/index.html in your browser to view the coverage report.
> 
> But it is actually in ./_deps/libocpp-build/ocpp_gcovr_coverage/index.html
> 
> Would it be possible to print the whole path there? Then it is easy to copy paste and directly put it in the browser. I could not find this line in the pull request?
> 
> But that's minor, would be nice if it's easy, otherwise it's ok like this.

That output is created by a post build command in our fork of CodeCoverage.cmake. I've created a PR to add that information: https://github.com/EVerest/everest-cmake/pull/18

2024-11-11 20:36 UTC, Pietfried approved these changes

2024-11-13 12:18 UTC, merged