Censor write only variables logging and added a new callback to sanitize any logging that would be passed to the existing message_callback
EVerest/libocpp pull request #911
Opened 2024-12-12 13:29 UTC by WilcodenBesten

## Describe your changes
1. Added optional callback to sanitize all logging before being passed to the existing message_callback. Can be used to remove secrets from log lines.
2. Added DeviceModel::get_mutability so the mutability of a component variable can be checked before the value change is logged. This prevents write-only varaiables to be logged

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [n/a] I have made corresponding changes to the documentation
- [n/a] If OCPP 2.0.1: I have updated the [OCPP 2.0.1 status document](https://github.com/EVerest/libocpp/tree/main/doc/ocpp_201_status.md)
- [x] I read the [contribution documentation](https://github.com/EVerest/EVerest/blob/main/CONTRIBUTING.md) and made sure that my changes meet its requirements

2024-12-12 13:31 UTC, WilcodenBesten commented
The log line here: https://github.com/EVerest/libocpp/blob/main/lib/ocpp/common/websocket/websocket_libwebsockets.cpp#L996 can still leak secrets as it's not filtered. You could argue that it's debug so that's not needed, but better safe then sorry imo. 

Would love to here you're opinion on that.

2024-12-20 15:30 UTC, hikinggrass requested changes

2024-12-20 15:30 UTC, hikinggrass commented on include/ocpp/common/ocpp_logging.hpp
> +    std::function<std::string(const std::string& message)> sanitize_message_callback;
As discussed in the last WG meeting, lets drop this callback from this PR and just merge the write only variable logging changes. I'll follow up with a generic solution

2025-01-06 09:06 UTC, marcemmers commented on include/ocpp/common/ocpp_logging.hpp
> +    std::function<std::string(const std::string& message)> sanitize_message_callback;
I removed the sanitizing so it should be ok like this

2025-01-06 09:14 UTC, hikinggrass commented on lib/ocpp/v201/charge_point.cpp
> +    std::function<std::string(const std::string& message)> sanitize_ocpp_messages_callback = nullptr;
That's not needed anymore

2025-01-06 09:15 UTC, marcemmers commented on lib/ocpp/v201/charge_point.cpp
> +    std::function<std::string(const std::string& message)> sanitize_ocpp_messages_callback = nullptr;
```suggestion
```

Yep, missed that

2025-01-06 09:50 UTC, hikinggrass approved these changes

2025-01-06 10:48 UTC, merged